name: Angular build to docs

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository letöltése
        uses: actions/checkout@v4

      - name: Node.js beállítása
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Függőségek telepítése
        run: npm ci

      - name: Angular build futtatása
        run: npx ng build

      - name: .nojekyll létrehozása
        run: touch docs/.nojekyll

      - name: Build eredmény commitolása
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build Angular app to docs"
          file_pattern: docs